### ISSUE TITLE
Couple quick questions

### ISSUE THREAD

**Issue by allenrowand** [skuep/GBB15#2]
No issues (yet), just questions:
1) Is there any reason why this couldn’t be used on a V2.4?
2) I want to confirm that if I want to use the CAN output I’d need to remove the 120 ohm resistor on the GBB and terminate at the toolhead

Thanks for your work, looking forward to installing this!

**Comment by skuep** [comment]
Hi there,
1. It has been designed to fit into small form factors. You can use it with the V2.4 probably (maybe thermal contact to the extrusion is not as good, because of the larger slot width). Other than that there is no real reason against it.
2. Yes, if the 120R is assembled (it's not by default) and the GBB15 is not at one of the two ends of the bus you need to remove it.
🤞👍

**Comment by allenrowand** [comment]
Thanks for the info. Maybe I’ll look into adding a plate between the GBB15 and 2020 to act as a heat spreader

**Comment by skuep** [comment]
That might work.. I would suggest you just try without one first, and check the PCB temp using the Integrated thermistor.
